-- Databricks notebook source
-- Insert the data in to T_MPB_PHS_WAC_TEMP from xlsx file
--01 DQ_MPB_PHS_WAC**
DELETE FROM {interDBName}.{interSchemaName}.T_MPB_PHS_WAC;

-- COMMAND ----------

--02 AQ_MPB_PHS_WAC
INSERT INTO {interDBName}.{interSchemaName}.T_MPB_PHS_WAC(CUSTOMER) SELECT CUSTOMER FROM psas_di_dev.340b_slvr.t_mpb_phs_wac_temp WHERE CUSTOMER Is Not Null And CUSTOMER<>'';

-- COMMAND ----------

--03 UQ_FormatAccountNumber
UPDATE {interDBName}.{interSchemaName}.T_MPB_PHS_WAC SET CUSTOMER = Concat(Left('000000',6-Len(CUSTOMER)), CUSTOMER) WHERE CUSTOMER Is Not Null And CUSTOMER<>'';

-- COMMAND ----------

--5
--02 AQ_PHS_ACCOUNTS
CREATE OR REPLACE TABLE psas_di_dev.340b_gold.T_PHS_ACCOUNTS AS
SELECT `CUST_ACCT_ID`, `CUST_NAME`, `STORE_NUM`, `DEA_FAMILY`, `MARKETING_CAMPAIGN`, `HOME_DC_ID`, `DEA_NUM`, `HIN_BASE_CD`, `HIN_DEPT_CD`, `HIN_LOCATION_CD`, `HIN_NUM`, 
IFF(LEFT(`ID_340B`,4)='0000','',`ID_340B`) AS `340B_ID`, 
`ATTENTION_NAME_DELY`, `ADDR_LINE_1_DELY`, `ADDR_LINE_2_DELY`, `CITY_NAME_DELY`, `STATE_CD_DELY`, `ZIP_CD_DELY`, 
`ATTENTION_NAME_INV`, `ADDR_LINE_1_INV`, `ADDR_LINE_2_INV`, `CITY_NAME_INV`, `STATE_CD_INV`, `ZIP_CD_INV`, 
`CUST_CHAIN_ID`, `CUST_CHAIN_NAME`, `NATIONAL_GROUP_CD`, `NATIONAL_GROUP_NAME`, `NATIONAL_SUB_GROUP_CD`, `NATIONAL_SUB_GROUP_NAME`, 
`REGION_NUM`, `REGION_NAME`, `DISTRICT_NUM`, `DISTRICT_NAME`, `RX_BILL_PLAN_CD`, `BUSINESS_TYPE_CD`, `DISTRIBUTION_CHANNEL`, 
`SALES_TERRITORY_ID`, `PRIMARY_CUST_ID`, 
IFF(`PROMO_SPEC_PRC_1`<>'',LEFT(`PROMO_SPEC_PRC_1`,2),'') AS `PROMO1`, 
IFF(`PROMO_SPEC_PRC_2`<>'',LEFT(`PROMO_SPEC_PRC_2`,2),'') AS `PROMO2`, 
IFF(`PROMO_SPEC_PRC_3`<>'',LEFT(`PROMO_SPEC_PRC_3`,2),'') AS `PROMO3`, 
IFF(`PROMO_SPEC_PRC_4`<>'',LEFT(`PROMO_SPEC_PRC_4`,2),'') AS `PROMO4`, 
IFF(`PROMO_SPEC_PRC_5`<>'',LEFT(`PROMO_SPEC_PRC_5`,2),'') AS `PROMO5`, 
IFF(`PROMO_SPEC_PRC_6`<>'',LEFT(`PROMO_SPEC_PRC_6`,2),'') AS `PROMO6`, 
`ACCOUNT_CLASSIFICATION`, `ACCOUNT_CLASSIFICATION_DESCRIPTION`
FROM psas_di_dev.340b_slvr.T_PHS_ACCOUNTS;

-- COMMAND ----------

--6
--03 DQ_PHS_MembershipRoster_Members
DELETE FROM psas_di_dev.340b_brnz.t_phs_membershiproster_members;

-- COMMAND ----------


-- 10 Q_Promo1
CREATE OR REPLACE TABLE PSAS_DI_DEV.340b_gold.T_Promo1 AS
SELECT DISTINCT T_PHS_ACCOUNTS.Cust_Acct_ID, T_PHS_ACCOUNTS.PROMO1
FROM psas_di_dev.`340b_gold`.T_PHS_ACCOUNTS AS T_PHS_ACCOUNTS INNER JOIN psas_di_dev.`340b_slvr`.T_TPV AS T_TPV ON T_PHS_ACCOUNTS.Promo1 = T_TPV.TPV;

-- COMMAND ----------


-- 11 Q_Promo2
CREATE OR REPLACE TABLE PSAS_DI_DEV.340b_gold.T_Promo2 AS
SELECT DISTINCT T_PHS_ACCOUNTS.Cust_Acct_ID, T_PHS_ACCOUNTS.Promo2
FROM PSAS_DI_DEV.340b_gold.T_PHS_ACCOUNTS AS T_PHS_ACCOUNTS INNER JOIN psas_di_dev.`340b_slvr`.T_TPV AS T_TPV ON T_PHS_ACCOUNTS.Promo2 = T_TPV.TPV;

-- COMMAND ----------


-- 12 Q_Promo3
CREATE OR REPLACE TABLE PSAS_DI_DEV.340b_gold.T_Promo3 AS
SELECT DISTINCT T_PHS_ACCOUNTS.Cust_Acct_ID, T_PHS_ACCOUNTS.Promo3
FROM PSAS_DI_DEV.340b_gold.T_PHS_ACCOUNTS AS T_PHS_ACCOUNTS INNER JOIN PSAS_DI_DEV.340b_slvr.T_TPV AS T_TPV ON T_PHS_ACCOUNTS.Promo3 = T_TPV.TPV;

-- COMMAND ----------


-- 13 Q_Promo4
CREATE OR REPLACE VIEW PSAS_DI_DEV.340b_gold.T_Promo4 AS
SELECT DISTINCT T_PHS_ACCOUNTS.Cust_Acct_ID, T_PHS_ACCOUNTS.Promo4
FROM PSAS_DI_DEV.340b_gold.T_PHS_ACCOUNTS AS T_PHS_ACCOUNTS INNER JOIN PSAS_DI_DEV.340b_SLVR.T_TPV AS T_TPV ON T_PHS_ACCOUNTS.Promo4 = T_TPV.TPV;

-- COMMAND ----------


-- 14 Q_Promo5
CREATE OR REPLACE VIEW PSAS_DI_DEV.340b_gold.T_Promo5 AS
SELECT DISTINCT T_PHS_ACCOUNTS.Cust_Acct_ID, T_PHS_ACCOUNTS.Promo5
FROM PSAS_DI_DEV.340b_gold.T_PHS_ACCOUNTS AS T_PHS_ACCOUNTS INNER JOIN PSAS_DI_DEV.340b_slvr.T_TPV AS T_TPV ON T_PHS_ACCOUNTS.Promo5 = T_TPV.TPV;

-- COMMAND ----------


CREATE OR REPLACE TABLE psas_di_dev.340b_gold.T_Promo6 AS
SELECT DISTINCT T_PHS_ACCOUNTS.Cust_Acct_ID, T_PHS_ACCOUNTS.Promo6
FROM psas_di_dev.`340b_gold`.T_PHS_ACCOUNTS AS T_PHS_ACCOUNTS INNER JOIN psas_di_dev.340b_slvr.T_TPV AS T_TPV ON T_PHS_ACCOUNTS.Promo6 = T_TPV.TPV;

-- COMMAND ----------


CREATE OR REPLACE TABLE psas_di_dev.340b_gold.T_PromoIDs AS
SELECT T_PHS_ACCOUNTS.Cust_Acct_ID, T_Promo1.Promo1 || T_Promo2.Promo2 || T_Promo3.Promo3 || T_Promo4.Promo4 || T_Promo5.Promo5 || T_Promo6.Promo6 AS PromoIDs
FROM (((((psas_di_dev.340b_gold.T_PHS_ACCOUNTS AS T_PHS_ACCOUNTS LEFT JOIN psas_di_dev.340b_gold.T_Promo1 ON T_PHS_ACCOUNTS.Cust_Acct_ID = T_Promo1.Cust_Acct_ID) LEFT JOIN psas_di_dev.340b_gold.T_Promo2 ON T_PHS_ACCOUNTS.Cust_Acct_ID = T_Promo2.Cust_Acct_ID) LEFT JOIN psas_di_dev.340b_gold.T_Promo3 ON T_PHS_ACCOUNTS.Cust_Acct_ID = T_Promo3.Cust_Acct_ID) LEFT JOIN psas_di_dev.340b_gold.T_Promo4 ON T_PHS_ACCOUNTS.Cust_Acct_ID = T_Promo4.Cust_Acct_ID) LEFT JOIN psas_di_dev.340b_gold.T_Promo5 ON T_PHS_ACCOUNTS.Cust_Acct_ID = T_Promo5.Cust_Acct_ID) LEFT JOIN psas_di_dev.340b_gold.T_Promo6 ON T_PHS_ACCOUNTS.Cust_Acct_ID = T_Promo6.Cust_Acct_ID
WHERE (((T_Promo1.Promo1 || T_Promo2.Promo2 || T_Promo3.Promo3 || T_Promo4.Promo4 || T_Promo5.Promo5 || T_Promo6.Promo6) Is Not Null));

-- COMMAND ----------

--[17 Q_PromoIDs]
CREATE OR REPLACE VIEW psas_di_dev.340b_gold.T_PromoIDs_17 AS
SELECT T_PromoIDs.Cust_Acct_ID, Left(PromoIDs,2) AS `3rd_Party_Vendor`,Len(PromoIDs) AS StringSize, IFF(StringSize>2,SUBSTR(PromoIDs,3,2),'') AS Secondary_Vendor, 
IFF(StringSize>4,SUBSTR(PromoIDs,5,2),'') AS Other_Vendors
FROM psas_di_dev.340b_gold.T_PromoIDs;

-- COMMAND ----------


--[18 Q_PromoIDs_FINAL]
CREATE OR REPLACE TABLE psas_di_dev.340b_gold.T_PromoIDs_FINAL AS
SELECT T_PromoIDs_17.Cust_Acct_ID, IFF(T_PromoIDs_17.`3rd_Party_Vendor`='M2' And T_PromoIDs_17.Secondary_Vendor<>'',T_PromoIDs_17.Secondary_Vendor,T_PromoIDs_17.`3rd_Party_Vendor`) AS `3rd_Party_Vendor1`, IFF(T_PromoIDs_17.`3rd_Party_Vendor`='M2' And T_PromoIDs_17.Secondary_Vendor<>'',T_PromoIDs_17.`3rd_Party_Vendor`,T_PromoIDs_17.Secondary_Vendor) AS Secondary_Vendor1, T_PromoIDs_17.Other_Vendors
FROM psas_di_dev.340b_gold.T_PromoIDs_17;

-- COMMAND ----------

--[19 Q_PromoIDs_FINAL2]
CREATE or REPLACE TABLE psas_di_dev.340b_gold.T_PromoIDs_FINAL2 AS 
SELECT T_PromoIDs_FINAL.Cust_Acct_ID, IFF(Secondary_Vendor1='CA',Secondary_Vendor1,`3rd_Party_Vendor1`) AS `3rd_Party_Vendor`, IFF(Secondary_Vendor1='CA',`3rd_Party_Vendor1`,Secondary_Vendor1) AS Secondary_Vendor, T_PromoIDs_FINAL.Other_Vendors
FROM psas_di_dev.340b_gold.T_PromoIDs_FINAL;

-- COMMAND ----------


-- 00 Q_Remove_585
CREATE OR REPLACE VIEW psas_di_dev.340b_gold.T_Remove_585 AS
SELECT T_PHS_ACCOUNTS.Cust_Acct_ID, T_PHS_ACCOUNTS.Cust_Chain_ID, T_PHS_ACCOUNTS.National_Group_Cd
FROM PSAS_DI_DEV.`340b_gold`.T_PHS_ACCOUNTS AS T_PHS_ACCOUNTS
WHERE (((T_PHS_ACCOUNTS.Cust_Chain_ID)='585') AND ((T_PHS_ACCOUNTS.National_Group_Cd)='0497' Or (T_PHS_ACCOUNTS.National_Group_Cd)='0498' Or (T_PHS_ACCOUNTS.National_Group_Cd)='0499'));

-- COMMAND ----------

INSERT INTO psas_di_dev.340b_brnz.t_phs_membershiproster_members(CUST_ACCT_ID, CUST_NAME, PVP_MEMBER_NAME, COVERED_ENTITY_PRIMARY, PHARMACY_NAME, CONTRACT_PHARMACY, CONTRACT_PHARMACY_PRIMARY, DEA_FAMILY, HOME_DC_ID, DEA_NUM, HIN_BASE_CD, HIN_DEPT_CD, HIN_LOCATION_CD, HIN_NUM, `340B_ID`, PVP_PARTICIPANT_ID, PVP_PARTICIPATION_FLAG, PVP_EFFECTIVE_DATE, PVP_EXPIRATION_DATE, ATTENTION_NAME_DELY, ADDR_LINE_1_DELY, ADDR_LINE_2_DELY, CITY_NAME_DELY, STATE_CD_DELY, ZIP_CD_DELY, ATTENTION_NAME_INV, ADDR_LINE_1_INV, ADDR_LINE_2_INV, CITY_NAME_INV, STATE_CD_INV, ZIP_CD_INV, CUST_CHAIN_ID, CUST_CHAIN_NAME, NATIONAL_GROUP_CD, NATIONAL_GROUP_NAME, NATIONAL_SUB_GROUP_CD, NATIONAL_SUB_GROUP_NAME, REGION_NUM, REGION_NAME, DISTRICT_NUM, DISTRICT_NAME, RX_BILL_PLAN_CD, BUSINESS_TYPE_CD, DISTRIBUTION_CHANNEL, SALES_TERRITORY_ID, PRIMARY_CUST_ID, THIRD_PARTY_VENDOR, SECONDARY_VENDOR, OTHER_VENDORS, ACCOUNT_CLASSIFICATION, ACCOUNT_CLASSIFICATION_DESCRIPTION, RECEIVED_DSCSA_AGREEMENT, EXTENDED_TO_MPB_YN) 
SELECT DISTINCT T_PHS_ACCOUNTS.Cust_Acct_ID, T_PHS_ACCOUNTS.Cust_Name, T_PHS_AUDIT.COVERED_ENTITY_NAME AS PVP_Member_Name, T_Pharmacy_Type_Data.CE_Primary AS Covered_Entity_Primary, T_Pharmacy_Type_Data.Pharmacy_Name AS Pharmacy_Name, 
IFF(Pharmacy_Type='Contract','Y','N') AS CONTRACT_PHARMACY, 
T_Pharmacy_Type_Data.CP_Primary AS CONTRACT_PHARMACY_PRIMARY, 
T_PHS_ACCOUNTS.DEA_Family AS DEA_FAMILY , T_PHS_ACCOUNTS.Home_DC_ID AS HOME_DC_ID , T_PHS_ACCOUNTS.DEA_Num AS DEA_NUM, 
T_PHS_ACCOUNTS.HIN_Base_Cd AS HIN_BASE_CD , T_PHS_ACCOUNTS.HIN_Dept_Cd AS HIN_DEPT_CD , T_PHS_ACCOUNTS.HIN_Location_Cd AS HIN_LOCATION_CD, 
T_PHS_ACCOUNTS.HIN_Num AS HIN_NUM , Trim(`340B_ID`) AS `340B_ID`, 
IFF(PVP_PARTICIPATION_FLAG='Y',T_PHS_AUDIT.PVP_PARTICIPANT_ID,'') AS PVP_Participant_ID,IFF(PVP_PARTICIPATION_FLAG='Y','Y','N') AS PVP_PARTICIPATION_FLAG, 
IFF(PVP_PARTICIPATION_FLAG='Y',PVP_ELIGIBILITY_DATE,NULL) AS PVP_EFFECTIVE_DATE , T_PHS_AUDIT.PVP_EXPIRATION_DATE AS PVP_EXPIRATION_DATE, 
T_PHS_ACCOUNTS.`ATTENTION_NAME_DELY` AS ATTENTION_NAME_DELY , T_PHS_ACCOUNTS.`ADDR_LINE_1_DELY` AS ADDR_LINE_1_DELY , 
T_PHS_ACCOUNTS.`ADDR_LINE_2_DELY` AS ADDR_LINE_2_DELY ,T_PHS_ACCOUNTS.`CITY_NAME_DELY` AS CITY_NAME_DELY , T_PHS_ACCOUNTS."STATE_CD_DELY" AS STATE_CD_DELY , 
T_PHS_ACCOUNTS."ZIP_CD_DELY" AS ZIP_CD_DELY , T_PHS_ACCOUNTS."ATTENTION_NAME_INV" AS ATTENTION_NAME_INV , T_PHS_ACCOUNTS."ADDR_LINE_1_INV" AS ADDR_LINE_1_INV , 
T_PHS_ACCOUNTS."ADDR_LINE_2_INV" AS ADDR_LINE_2_INV , T_PHS_ACCOUNTS."CITY_NAME_INV" AS CITY_NAME_INV , T_PHS_ACCOUNTS."STATE_CD_INV" AS STATE_CD_INV , 
T_PHS_ACCOUNTS."ZIP_CD_INV" AS ZIP_CD_INV , T_PHS_ACCOUNTS.Cust_Chain_ID AS CUST_CHAIN_ID , T_PHS_ACCOUNTS.Cust_Chain_Name AS CUST_CHAIN_NAME , 
T_PHS_ACCOUNTS.National_Group_Cd AS NATIONAL_GROUP_CD , T_PHS_ACCOUNTS.National_Group_Name AS NATIONAL_GROUP_NAME , T_PHS_ACCOUNTS.National_Sub_Group_Cd AS NATIONAL_SUB_GROUP_CD , 
T_PHS_ACCOUNTS.National_Sub_Group_Name AS NATIONAL_SUB_GROUP_NAME , 
T_PHS_ACCOUNTS.Region_Num AS REGION_NUM , T_PHS_ACCOUNTS.Region_Name AS REGION_NAME , 
T_PHS_ACCOUNTS.District_Num AS DISTRICT_NUM , T_PHS_ACCOUNTS.District_Name AS DISTRICT_NAME , T_PHS_ACCOUNTS.Rx_Bill_Plan_Cd AS RX_BILL_PLAN_CD , 
T_PHS_ACCOUNTS.Business_Type_Cd AS BUSINESS_TYPE_CD , T_PHS_ACCOUNTS.Distribution_Channel AS DISTRIBUTION_CHANNEL , 
T_PHS_ACCOUNTS.Sales_Territory_ID AS SALES_TERRITORY_ID , T_PHS_ACCOUNTS.Primary_Cust_ID AS PRIMARY_CUST_ID , 
T_PromoIDs_FINAL2."3rd_Party_Vendor" AS THIRD_PARTY_VENDOR , V_PromoIDs_FINAL2.Secondary_Vendor AS SECONDARY_VENDOR , 
V_PromoIDs_FINAL2.Other_Vendors AS OTHER_VENDORS , T_PHS_ACCOUNTS.Account_Classification AS ACCOUNT_CLASSIFICATION , 
T_PHS_ACCOUNTS.Account_Classification_Description AS ACCOUNT_CLASSIFICATION_DESCRIPTION , 
T_PHS_AUDIT.DSCSA_RECEIVED AS RECEIVED_DSCSA_AGREEMENT ,IFF(T_MPB_PHS_WAC.MPB_EXTENDED = NULL,'NO','YES') AS EXTENDED_TO_MPB_YN
FROM (((((T_PHS_ACCOUNTS AS T_PHS_ACCOUNTS INNER JOIN psas_di_dev.340b_gold.T_PHS_AUDIT AS T_PHS_AUDIT ON T_PHS_ACCOUNTS.Cust_Acct_ID = T_PHS_AUDIT.CUST_ACCT_ID) LEFT JOIN {interDBName}.{interSchemaName}.T_MPB_PHS_WAC AS T_MPB_PHS_WAC ON 
T_PHS_ACCOUNTS.Cust_Acct_ID = T_MPB_PHS_WAC.CUSTOMER)LEFT JOIN V_Remove_585 ON T_PHS_ACCOUNTS.Cust_Acct_ID = V_Remove_585.Cust_Acct_ID) 
LEFT JOIN T_PromoIDs_FINAL2 ON T_PHS_ACCOUNTS.Cust_Acct_ID = T_PromoIDs_FINAL2.Cust_Acct_ID) 
LEFT JOIN psas_di_dev.340b_slvr.T_LUTL_NON_ORDERING_ACCOUNTS AS T_LUTL_NON_ORDERING_ACCOUNTS ON T_PHS_ACCOUNTS.Cust_Acct_ID = T_LUTL_NON_ORDERING_ACCOUNTS.Cust_Acct_ID) 
LEFT JOIN psas_di_dev.340b_slvr.t_pharmacy_type_data AS T_Pharmacy_Type_Data ON T_PHS_ACCOUNTS.Cust_Acct_ID = T_Pharmacy_Type_Data.Cust_Acct
WHERE (((T_PHS_ACCOUNTS.Cust_Chain_ID) Not In ('000','770')) AND ((T_PHS_ACCOUNTS.Business_Type_Cd)<>'31') AND ((T_PHS_ACCOUNTS.Account_Classification) in ('004','005')) AND ((T_Remove_585.Cust_Chain_ID) Is Null) AND ((T_LUTL_NON_ORDERING_ACCOUNTS.ID) Is Null));

-- COMMAND ----------

-- Opace daily table not exists
UPDATE psas_di_dev.340b_slvr.T_PHS_MembershipRoster_Members AS T_PHS_MembershipRoster_Members SET T_PHS_MembershipRoster_Members.PVP_Member_Name = OPACE_DAILY_PUBLIC.Entity_Name from PRD_ENT_DL_US_EXT_340B_DB.RAWDATA.OPACE_DAILY_PUBLIC AS OPACE_DAILY_PUBLIC
WHERE ((T_PHS_MembershipRoster_Members."340B_ID" = OPACE_DAILY_PUBLIC."ID_340B") AND ((T_PHS_MembershipRoster_Members.PVP_Member_Name) Is Null));

-- COMMAND ----------


--06 DQ_PHS_MembershipRoster_WAC
DELETE FROM psas_di_dev.340b_slvr.T_PHS_MembershipRoster_WAC;

-- COMMAND ----------

--didn't execute 
--07 AQ_PHS_MembershipRoster_WAC
INSERT INTO psas_di_dev.340b_slvr.T_PHS_MembershipRoster_WAC (
    CUST_ACCT_ID, CUST_NAME, `340B_ID`, PVP_PARTICIPANT_ID, PVP_PARTICIPATION_FLAG, 
    PVP_MEMBER_NAME, PVP_EFFECTIVE_DATE, PVP_EXPIRATION_DATE, STORE_NUM, DEA_FAMILY, 
    MARKETING_CAMPAIGN, HOME_DC_ID, DEA_NUM, HIN_BASE_CD, HIN_DEPT_CD, HIN_LOCATION_CD, 
    HIN_NUM, ATTENTION_NAME_DELY, ADDR_LINE_1_DELY, ADDR_LINE_2_DELY, CITY_NAME_DELY, 
    STATE_CD_DELY, ZIP_CD_DELY, ATTENTION_NAME_INV, ADDR_LINE_1_INV, ADDR_LINE_2_INV, 
    CITY_NAME_INV, STATE_CD_INV, ZIP_CD_INV, CUST_CHAIN_ID, CUST_CHAIN_NAME, 
    NATIONAL_GROUP_CD, NATIONAL_GROUP_NAME, NATIONAL_SUB_GROUP_CD, NATIONAL_SUB_GROUP_NAME, 
    REGION_NUM, REGION_NAME, DISTRICT_NUM, DISTRICT_NAME, RX_BILL_PLAN_CD, BUSINESS_TYPE_CD, 
    DISTRIBUTION_CHANNEL, SALES_TERRITORY_ID, PRIMARY_CUST_ID, `3RD_PARTY_VENDOR`, 
    SECONDARY_VENDOR, OTHER_VENDORS, ACCOUNT_CLASSIFICATION, ACCOUNT_CLASSIFICATION_DESCRIPTION
)
SELECT DISTINCT 
    T_PHS_ACCOUNTS.CUST_ACCT_ID AS CUST_ACCT_ID,
    T_PHS_ACCOUNTS.CUST_NAME AS CUST_NAME,
    T_PHS_AUDIT.PHS_340B_ID AS `340B_ID`,
    T_PHS_AUDIT.PVP_PARTICIPANT_ID AS PVP_PARTICIPANT_ID,
    T_PHS_AUDIT.PVP_PARTICIPATION_FLAG AS PVP_PARTICIPATION_FLAG,
    T_PHS_AUDIT.PVP_MEMBER_NAME AS PVP_MEMBER_NAME,
    IFF(PVP_PARTICIPATION_FLAG='Y', PVP_ELIGIBILITY_DATE, NULL) AS PVP_EFFECTIVE_DATE,
    T_PHS_AUDIT.PVP_EXPIRATION_DATE AS PVP_EXPIRATION_DATE,
    T_PHS_ACCOUNTS.STORE_NUM AS STORE_NUM,
    T_PHS_ACCOUNTS.DEA_FAMILY AS DEA_FAMILY,
    T_PHS_ACCOUNTS.MARKETING_CAMPAIGN AS MARKETING_CAMPAIGN,
    T_PHS_ACCOUNTS.HOME_DC_ID AS HOME_DC_ID,
    T_PHS_ACCOUNTS.DEA_NUM AS DEA_NUM,
    T_PHS_ACCOUNTS.HIN_BASE_CD AS HIN_BASE_CD,
    T_PHS_ACCOUNTS.HIN_DEPT_CD AS HIN_DEPT_CD,
    T_PHS_ACCOUNTS.HIN_LOCATION_CD AS HIN_LOCATION_CD,
    T_PHS_ACCOUNTS.HIN_NUM AS HIN_NUM,
    T_PHS_ACCOUNTS.ATTENTION_NAME_DELY AS ATTENTION_NAME_DELY,
    T_PHS_ACCOUNTS.ADDR_LINE_1_DELY AS ADDR_LINE_1_DELY,
    T_PHS_ACCOUNTS.ADDR_LINE_2_DELY AS ADDR_LINE_2_DELY,
    T_PHS_ACCOUNTS.CITY_NAME_DELY AS CITY_NAME_DELY,
    T_PHS_ACCOUNTS.STATE_CD_DELY AS STATE_CD_DELY,
    T_PHS_ACCOUNTS.ZIP_CD_DELY AS ZIP_CD_DELY,
    T_PHS_ACCOUNTS.ATTENTION_NAME_INV AS ATTENTION_NAME_INV,
    T_PHS_ACCOUNTS.ADDR_LINE_1_INV AS ADDR_LINE_1_INV,
    T_PHS_ACCOUNTS.ADDR_LINE_2_INV AS ADDR_LINE_2_INV,
    T_PHS_ACCOUNTS.CITY_NAME_INV AS CITY_NAME_INV,
    T_PHS_ACCOUNTS.STATE_CD_INV AS STATE_CD_INV,
    T_PHS_ACCOUNTS.ZIP_CD_INV AS ZIP_CD_INV,
    T_PHS_ACCOUNTS.CUST_CHAIN_ID AS CUST_CHAIN_ID,
    T_PHS_ACCOUNTS.CUST_CHAIN_NAME AS CUST_CHAIN_NAME,
    T_PHS_ACCOUNTS.NATIONAL_GROUP_CD AS NATIONAL_GROUP_CD,
    T_PHS_ACCOUNTS.NATIONAL_GROUP_NAME AS NATIONAL_GROUP_NAME,
    T_PHS_ACCOUNTS.NATIONAL_SUB_GROUP_CD AS NATIONAL_SUB_GROUP_CD,
    T_PHS_ACCOUNTS.NATIONAL_SUB_GROUP_NAME AS NATIONAL_SUB_GROUP_NAME,
    T_PHS_ACCOUNTS.REGION_NUM AS REGION_NUM,
    T_PHS_ACCOUNTS.REGION_NAME AS REGION_NAME,
    T_PHS_ACCOUNTS.DISTRICT_NUM AS DISTRICT_NUM,
    T_PHS_ACCOUNTS.DISTRICT_NAME AS DISTRICT_NAME,
    T_PHS_ACCOUNTS.RX_BILL_PLAN_CD AS RX_BILL_PLAN_CD,
    T_PHS_ACCOUNTS.BUSINESS_TYPE_CD AS BUSINESS_TYPE_CD,
    T_PHS_ACCOUNTS.DISTRIBUTION_CHANNEL AS DISTRIBUTION_CHANNEL,
    T_PHS_ACCOUNTS.SALES_TERRITORY_ID AS SALES_TERRITORY_ID,
    T_PHS_ACCOUNTS.PRIMARY_CUST_ID AS PRIMARY_CUST_ID,
    T_PromoIDs_FINAL2.`3rd_Party_Vendor` AS `3RD_PARTY_VENDOR`,
    T_PromoIDs_FINAL2.SECONDARY_VENDOR AS SECONDARY_VENDOR,
    T_PromoIDs_FINAL2.OTHER_VENDORS AS OTHER_VENDORS,
    T_PHS_ACCOUNTS.ACCOUNT_CLASSIFICATION AS ACCOUNT_CLASSIFICATION,
    T_PHS_ACCOUNTS.ACCOUNT_CLASSIFICATION_DESCRIPTION AS ACCOUNT_CLASSIFICATION_DESCRIPTION
FROM 
    (PSAS_DI_DEV.340B_GOLD.T_PHS_ACCOUNTS AS T_PHS_ACCOUNTS
    INNER JOIN PSAS_DI_DEV.340B_GOLD.T_PHS_AUDIT AS T_PHS_AUDIT 
    ON T_PHS_ACCOUNTS.CUST_ACCT_ID = T_PHS_AUDIT.CUST_ACCT_ID)
    LEFT JOIN PSAS_DI_DEV.340B_SLVR.T_LUTL_NON_ORDERING_ACCOUNTS AS T_LUTL_NON_ORDERING_ACCOUNTS 
    ON T_PHS_ACCOUNTS.CUST_ACCT_ID = T_LUTL_NON_ORDERING_ACCOUNTS.CUST_ACCT_ID
    LEFT JOIN psas_di_dev.340b_gold.t_promoids_final2
    ON T_PHS_ACCOUNTS.CUST_ACCT_ID = T_PromoIDs_FINAL2.CUST_ACCT_ID
WHERE 
    T_PHS_ACCOUNTS.CUST_CHAIN_ID <> '989' 
    AND T_PHS_ACCOUNTS.BUSINESS_TYPE_CD <> '31' 
    AND T_PHS_ACCOUNTS.ACCOUNT_CLASSIFICATION = '003' 
    AND T_PHS_AUDIT.STATUS = 'ACTIVE' 
    AND CHARINDEX('TEMPLATE', T_PHS_ACCOUNTS.CUST_NAME) = 0 
    AND T_LUTL_NON_ORDERING_ACCOUNTS.ID IS NULL
ORDER BY 
    T_PHS_ACCOUNTS.CUST_ACCT_ID;

-- COMMAND ----------

E--08 UQ_PHS_MembershipRoster_WAC_MissingPVPName
--OPACE DAILY DOEN'T EXISTS
UPDATE PSAS_DI_DEV.340B_SLVR.T_PHS_MembershipRoster_WAC AS T_PHS_MembershipRoster_WAC SET T_PHS_MembershipRoster_WAC.PVP_Member_Name = OPACE_DAILY_PUBLIC.Entity_Name from PRD_ENT_DL_US_EXT_340B_DB.RAWDATA.OPACE_DAILY_PUBLIC AS OPACE_DAILY_PUBLIC
WHERE ((T_PHS_MembershipRoster_WAC."340B_ID" = OPACE_DAILY_PUBLIC."ID_340B") AND ((T_PHS_MembershipRoster_WAC.PVP_Member_Name) Is Null));

-- COMMAND ----------


--Q_NON_ORDERING_ACCOUNTSg
CREATE OR REPLACE table PSAS_DI_DEV.340B_gold.T_NON_ORDERING_ACCOUNTS AS
SELECT T_LUTL_NON_ORDERING_ACCOUNTS.Cust_Acct_ID, T_PHS_AUDIT.CUST_ACCT_NAME, T_PHS_AUDIT.CUST_CHN_ID, T_PHS_AUDIT.STATUS
FROM PSAS_DI_DEV.340B_SLVR.T_LUTL_NON_ORDERING_ACCOUNTS AS T_LUTL_NON_ORDERING_ACCOUNTS LEFT JOIN PSAS_DI_DEV.340B_gold.T_PHS_AUDIT AS T_PHS_AUDIT ON T_LUTL_NON_ORDERING_ACCOUNTS.Cust_Acct_ID = T_PHS_AUDIT.CUST_ACCT_ID;

-- COMMAND ----------


--01 Q_PHS_MembershipRoster_WAC_PotentialMissing
CREATE OR REPLACE TABLE psas_di_dev.340b_slvr.T_PHS_MembershipRoster_WAC_PotentialMissing AS
SELECT T_PHS_AUDIT.CUST_ACCT_ID, T_PHS_AUDIT.CUST_ACCT_NAME, T_PHS_AUDIT.SALES_ADMIN, T_PHS_AUDIT.MHS_SALES_REP, T_PHS_AUDIT.PHS_340B_ID, 
T_PHS_AUDIT.ACCT_CLASSIFICATION, T_PHS_AUDIT.ACTIVATION_DATE, T_PHS_AUDIT.COMMENTS, T_PHS_AUDIT.LEADS_WAC, T_PHS_AUDIT.ACCT_NAME_A34, 
T_PHS_AUDIT.ACCT_NAME_C34, T_PHS_AUDIT.CUST_CHN_ID, T_PHS_AUDIT.CHAIN_NAM, T_PHS_AUDIT.HOME_DC_ID, T_PHS_AUDIT.STATUS, 
T_PHS_MembershipRoster_WAC.PVP_Participant_ID, T_PHS_MembershipRoster_WAC.PVP_Participation_Flag, T_PHS_MembershipRoster_WAC.PVP_Effective_Date, 
T_PHS_MembershipRoster_WAC.PVP_Expiration_Date
FROM (psas_di_dev.340b_gold.T_PHS_AUDIT AS T_PHS_AUDIT  LEFT JOIN psas_di_dev.340b_gold.T_NON_ORDERING_ACCOUNTS ON T_PHS_AUDIT.CUST_ACCT_ID = T_NON_ORDERING_ACCOUNTS.Cust_Acct_ID) 
LEFT JOIN psas_di_dev.340b_slvr.T_PHS_MembershipRoster_WAC AS T_PHS_MembershipRoster_WAC ON T_PHS_AUDIT.CUST_ACCT_ID = T_PHS_MembershipRoster_WAC.Cust_Acct_ID
WHERE (((T_PHS_AUDIT.CUST_CHN_ID) Not In ('989','060')) AND ((T_PHS_AUDIT.HOME_DC_ID) Not In ('8589','8199')) AND ((T_PHS_AUDIT.STATUS)='ACTIVE') 
AND ((CHARINDEX('Y', ACCT_NAME_A34 || ACCT_NAME_C34 || LEADS_WAC))<>0) AND ((T_NON_ORDERING_ACCOUNTS.CUST_ACCT_NAME) Is Null) 
AND ((T_PHS_MembershipRoster_WAC.Cust_Name) Is Null))
ORDER BY T_PHS_AUDIT.CUST_CHN_ID;

-- COMMAND ----------


--01 Q_PHS_MembershipRoster_Members_PotentialMissing
CREATE OR REPLACE TABLE  psas_di_dev.340b_gold.340b_T_PHS_MembershipRoster_Members_PotentialMissing AS
SELECT T_PHS_AUDIT.CUST_ACCT_ID, T_PHS_AUDIT.CUST_ACCT_NAME, T_PHS_AUDIT.PHS_340B_ID, T_PHS_AUDIT.ROUTE, 
T_PHS_AUDIT.STOP, T_PHS_AUDIT.UPDATE_SAP AS Created, T_PHS_AUDIT.SALES_CURMTH, T_PHS_AUDIT.ACCT_CLASSIFICATION AS Acct_Class, T_PHS_AUDIT.COMMENTS, 
T_PHS_AUDIT.ACCT_NAME_PHS, T_PHS_AUDIT.LEADS_PHS, T_PHS_AUDIT.CUST_CHN_ID, T_PHS_AUDIT.CHAIN_NAM, T_PHS_AUDIT.HOME_DC_ID, T_PHS_AUDIT.STATUS
FROM (psas_di_dev.340b_gold.T_PHS_AUDIT AS T_PHS_AUDIT  LEFT JOIN psas_di_dev.340b_brnz.t_phs_membershiproster_members AS T_PHS_MembershipRoster_Members ON T_PHS_AUDIT.CUST_ACCT_ID = T_PHS_MembershipRoster_Members.Cust_Acct_ID) LEFT JOIN psas_di_dev.340b_gold.T_NON_ORDERING_ACCOUNTS 
ON T_PHS_AUDIT.CUST_ACCT_ID = T_NON_ORDERING_ACCOUNTS.Cust_Acct_ID
WHERE (((T_PHS_AUDIT.ACCT_NAME_PHS)='Y') AND ((T_PHS_AUDIT.CUST_CHN_ID) Not In ('314','585','989','060','770')) AND ((T_PHS_AUDIT.HOME_DC_ID) 
Not In ('8589','8199')) AND ((T_PHS_AUDIT.STATUS)='ACTIVE') AND ((T_PHS_MembershipRoster_Members.Cust_Name) Is Null) AND ((T_NON_ORDERING_ACCOUNTS.CUST_ACCT_NAME) Is Null)) OR (((T_PHS_AUDIT.LEADS_PHS)='Y') 
AND ((T_PHS_AUDIT.CUST_CHN_ID) Not In ('314','585','989','060','770')) AND ((T_PHS_AUDIT.HOME_DC_ID) Not In ('8589','8199')) 
AND ((T_PHS_AUDIT.STATUS)='ACTIVE') AND ((T_PHS_MembershipRoster_Members.Cust_Name) Is Null) AND ((T_NON_ORDERING_ACCOUNTS.CUST_ACCT_NAME) Is Null))
ORDER BY T_PHS_AUDIT.UPDATE_SAP;

-- COMMAND ----------


--09 Q_PHS_Count
CREATE OR REPLACE TABLE psas_di_dev.340b_brnz.T_PHS_Count AS
SELECT Count(T_PHS_MembershipRoster_Members.CUST_ACCT_ID) AS PHS_TOTAL
FROM psas_di_dev.340b_brnz.t_phs_membershiproster_members AS T_PHS_MembershipRoster_Members;


-- COMMAND ----------

--10 Q_WAC_Count
CREATE OR REPLACE TABLE PSAS_DI_DEV.340B_GOLD.T_WAC_Count AS
SELECT Count(T_PHS_MembershipRoster_WAC.CUST_ACCT_ID) AS WAC_TOTAL
FROM psas_di_dev.340b_slvr.t_phs_membershiproster_wac AS T_PHS_MembershipRoster_WAC;

-- COMMAND ----------

--tables mising not executed
--11a PTQ_Termed_Accounts_PreviousMonth
CREATE OR REPLACE TABLE T_PTQ_Termed_Accounts_PreviousMonth AS
SELECT DISTINCT COUNT(CA.CUST_ACCT_ID) AS TERMED_ACCTS_PREVIOUS_MONTH
FROM "PRD_PSAS_DB"."RPT".T_DM_VSTX_CUST_ORG V
INNER JOIN dev_psas_db.rpt.t_iw_cust_acct CA
ON V.CUST_ACCT_ID = CA.CUST_ACCT_ID
INNER JOIN dev_psas_db.rpt.t_dm_vstx_cust VC
ON V.CUST_ACCT_ID = VC.CUST_ACCT_ID
WHERE VC.MCK_KU_ACCT_CLAS in ('004','005') AND CA.ACTIVE_CUST_IND = 'I' AND CA.CUST_CHN_ID <> '989'
AND V.TERM_DT BETWEEN DATE_TRUNC('MONTH', ADD_MONTHS(CURRENT_TIMESTAMP(),-1)) AND LAST_DAY(ADD_MONTHS(CURRENT_TIMESTAMP(),-1));

-- COMMAND ----------


--11b PTQ_Termed_Accounts_CurrentMonth
CREATE OR REPLACE TABLE T_PTQ_Termed_Accounts_CurrentMonth AS
SELECT DISTINCT COUNT(CA.CUST_ACCT_ID) AS TERMED_ACCTS_CURRENT_MONTH
FROM "PRD_PSAS_DB"."RPT".T_DM_VSTX_CUST_ORG V
INNER JOIN dev_psas_db.rpt.t_iw_cust_acct CA
ON V.CUST_ACCT_ID = CA.CUST_ACCT_ID
INNER JOIN dev_psas_db.rpt.t_dm_vstx_cust VC
ON V.CUST_ACCT_ID = VC.CUST_ACCT_ID
WHERE VC.MCK_KU_ACCT_CLAS in ('004','005') AND CA.ACTIVE_CUST_IND = 'I' AND CA.CUST_CHN_ID <> '989'
AND V.TERM_DT BETWEEN DATE_TRUNC('MONTH', ADD_MONTHS(CURRENT_TIMESTAMP(),0)) AND LAST_DAY(ADD_MONTHS(CURRENT_TIMESTAMP(),0));

-- COMMAND ----------

---TABLES MISSING--
12 Q_Totals_Month_To_Date
CREATE OR REPLACE TABLE PSAS_DI_DEV.340B_GOLD.T_Totals_Month_To_Date AS
SELECT T_PHS_Count.PHS_Total, T_WAC_Count.WAC_Total, T_PTQ_Termed_Accounts_PreviousMonth.TERMED_ACCTS_PREVIOUS_MONTH, T_PTQ_Termed_Accounts_CurrentMonth.TERMED_ACCTS_CURRENT_MONTH
FROM psas_di_dev.340b_brnz.t_phs_count, psas_di_dev.340b_gold.t_wac_count, T_PTQ_Termed_Accounts_PreviousMonth, T_PTQ_Termed_Accounts_CurrentMonth;
