-- Databricks notebook source
-- MAGIC %python
-- MAGIC ---00 PTQ_SQL_DMEM
-- MAGIC CREATE OR REPLACE VIEW V_PTQ_SQL_DMEM_00 AS SELECT CA.CUST_ACCT_ID, CUST_ACCT_NAM, CE.CNTRCT_LEAD_ID, L.LEAD_NAME,
-- MAGIC L.LEAD_TYPE, CE.PRTY_CONT, CE.MARKUP_CONT, CE.CONT_PREFD
-- MAGIC FROM PRD_PSAS_DB.RPT.T_IW_CUST_ACCT CA INNER JOIN PRD_PSAS_DB.RPT.T_DCON_CONT_ELIG CE
-- MAGIC ON CA.CUST_ACCT_ID  = CE.CUST_ACCT_ID 
-- MAGIC INNER JOIN PRD_PSAS_DB.RPT.T_CMS_LEAD L
-- MAGIC ON CE.CNTRCT_LEAD_ID = L.CNTRC_LEAD_ID
-- MAGIC INNER JOIN PRD_PSAS_DB.RPT.T_DM_VSTX_CUST X ON CA.CUST_ACCT_ID = X.CUST_ACCT_ID
-- MAGIC WHERE (X.MCK_KU_CHNL_TYP = '20' OR (X.MCK_KU_CHNL_TYP = '50' AND SUBSTRING(CA.CUST_ACCT_NAM, LENGTH(CA.CUST_ACCT_NAM) - 2, 3) = 'PHS')) AND CA.ACTIVE_CUST_IND = 'A' AND CA.CUST_CHN_ID <> '989';
-- MAGIC
-- MAGIC
-- MAGIC --CREATE OR REPLACE VIEW V_PTQ_DMEM_00 SELECT 00 PTQ_SQL_DMEM].CUST_ACCT_ID, 00 PTQ_SQL_DMEM].CUST_ACCT_NAM, 00 PTQ_SQL_DMEM].CNTRCT_LEAD_ID, 00 PTQ_SQL_DMEM].LEAD_NAME, 00 PTQ_SQL_DMEM].LEAD_TYPE, 00 PTQ_SQL_DMEM].PRTY_CONT, 00 PTQ_SQL_DMEM].MARKUP_CONT, 00 PTQ_SQL_DMEM].CONT_PREFD
-- MAGIC --FROM V_PTQ_SQL_DMEM_00;
-- MAGIC
-- MAGIC --02 AQ_Account_DMEM_List
-- MAGIC INSERT INTO {interDBName}.{interSchemaName}.T_DMEM_LIST( CUST_ACCT_ID, CNTRCT_LEAD_ID, LEAD_NAME, LEAD_TYPE, PRTY_CONT, MARKUP_CONT, CONT_PREFD )
-- MAGIC SELECT VPSD00.CUST_ACCT_ID, VPSD00.CNTRCT_LEAD_ID, VPSD00.LEAD_NAME, VPSD00.LEAD_TYPE, VPSD00.PRTY_CONT, VPSD00.MARKUP_CONT, VPSD00.CONT_PREFD
-- MAGIC FROM V_PTQ_SQL_DMEM_00 AS VPSD00;
-- MAGIC
-- MAGIC
-- MAGIC ---02b DQ_RemoveWrong_AcctClass
-- MAGIC --Issue with this query --Distinctrow updates the records 
-- MAGIC
-- MAGIC --*************************DELETE DISTINCTROW T_DMEM_List.*, T_PHS_AUDIT.ACCT_CLASSIFICATION Need Confirmation
-- MAGIC --FROM T_DMEM_List LEFT JOIN T_PHS_AUDIT ON T_DMEM_List.CUST_ACCT_ID = T_PHS_AUDIT.CUST_ACCT_ID
-- MAGIC --WHERE (((T_PHS_AUDIT.ACCT_CLASSIFICATION) Not In ("003","004","005")));
-- MAGIC --SELECT * FROM T_DMEM_LIST AS A WHERE EXISTS( SELECT 1 FROM T_PHS_AUDIT AS B WHERE B.CUST_ACCT_ID = A.CUST_ACCT_ID AND (B.ACCT_CLASSIFICATION != '003' AND B.ACCT_CLASSIFICATION not in ('004','005')) );
-- MAGIC DELETE FROM {interDBName}.{interSchemaName}.T_DMEM_LIST AS A WHERE EXISTS( SELECT 1 FROM {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS B WHERE B.CUST_ACCT_ID = A.CUST_ACCT_ID AND (B.ACCT_CLASSIFICATION != '003' AND B.ACCT_CLASSIFICATION not in ('004','005')) );
-- MAGIC
-- MAGIC --03 DQ_Lead_List
-- MAGIC
-- MAGIC DELETE FROM {interDBName}.{interSchemaName}.T_MT_LEAD_LIST;
-- MAGIC
-- MAGIC ---04 AQ_Lead_List
-- MAGIC INSERT INTO {interDBName}.{interSchemaName}.T_MT_LEAD_LIST ( CNTRCT_LEAD_ID, CNTRCT_LEAD_NAME, CNTRCT_LEAD_TYPE )
-- MAGIC SELECT DISTINCT A.CNTRCT_LEAD_ID AS CNTRCT_LEAD_ID, A.LEAD_NAME AS CNTRCT_LEAD_NAME, A.LEAD_TYPE AS CNTRCT_LEAD_TYPE
-- MAGIC FROM {interDBName}.{interSchemaName}.T_DMEM_LIST AS A WHERE A.CNTRCT_LEAD_ID IS NOT NULL;
-- MAGIC
-- MAGIC
-- MAGIC ---05 DQ_Account_List --- fEW RECORDS ARE MISSION FOR PHS AUDIT AND LUL ENTITY NEED TO REFRESHED 
-- MAGIC
-- MAGIC DELETE FROM {interDBName}.{interSchemaName}.T_MT_ACCOUNT_LIST;
-- MAGIC
-- MAGIC ---06 AQ_Account_List
-- MAGIC INSERT INTO {interDBName}.{interSchemaName}.T_MT_ACCOUNT_LIST ( CUST_ACCT_ID, CUST_ACCT_NAME, CUST_CHN_ID, ENTITY_TYPE, EXPANSION_ENTITY, ACCT_CLASSIFICATION )
-- MAGIC SELECT A.CUST_ACCT_ID, A.CUST_ACCT_NAME, A.CUST_CHN_ID, A.ENTITY_TYPE, B.EXPANSION_ENTITY, A.ACCT_CLASSIFICATION 
-- MAGIC FROM {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS A INNER JOIN {coreDBName}.{coreSchemaName}.T_LUTL_ENTITY AS B ON A.ENTITY_TYPE = B.ENTITY_TYPE
-- MAGIC WHERE (A.CUST_CHN_ID != '989') AND (A.ACCT_CLASSIFICATION='003' OR A.ACCT_CLASSIFICATION in ('004','005')) AND (UPPER(A.STATUS)='ACTIVE');
-- MAGIC
-- MAGIC
-- MAGIC ---07 DQ_MainLead
-- MAGIC
-- MAGIC DELETE FROM {interDBName}.{interSchemaName}.T_MAINLEAD;
-- MAGIC
-- MAGIC ----08 AQ_MainLead
-- MAGIC INSERT INTO {interDBName}.{interSchemaName}.T_MAINLEAD(CUST_ACCT_ID, CNTRCT_LEAD_ID)
-- MAGIC SELECT DISTINCT A.CUST_ACCT_ID, B.CNTRCT_LEAD_ID
-- MAGIC FROM {interDBName}.{interSchemaName}.T_MT_ACCOUNT_LIST AS A INNER JOIN {interDBName}.{interSchemaName}.T_DMEM_LIST AS B ON A.CUST_ACCT_ID = B.CUST_ACCT_ID WHERE (B.CNTRCT_LEAD_ID='178018' OR B.CNTRCT_LEAD_ID='181126');
-- MAGIC
-- MAGIC -------09 UQ_MainLead --Need To check 
-- MAGIC ---Need Validation 
-- MAGIC UPDATE {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS A SET A.MAIN_LEAD = B.CNTRCT_LEAD_ID FROM {interDBName}.{interSchemaName}.T_MAINLEAD AS B 
-- MAGIC WHERE (A.CUST_ACCT_ID = B.CUST_ACCT_ID) AND (A.MAIN_LEAD IS NULL OR A.MAIN_LEAD != B.CNTRCT_LEAD_ID);
-- MAGIC
-- MAGIC --UPDATE T_PHS_AUDIT INNER JOIN T_MainLead ON T_PHS_AUDIT.CUST_ACCT_ID = T_MainLead.CUST_ACCT_ID SET T_PHS_AUDIT.MAIN_LEAD = [CNTRCT_LEAD_ID]
-- MAGIC --WHERE (((T_PHS_AUDIT.MAIN_LEAD) Is Null Or (T_PHS_AUDIT.MAIN_LEAD)<>[CNTRCT_LEAD_ID]));
-- MAGIC
-- MAGIC
-- MAGIC -------------------------------------Part 2----------------------
-- MAGIC
-- MAGIC ---# Data should be clean in T_MT_WAC_DMEM or not
-- MAGIC --03 DQ_WAC_DMEM
-- MAGIC DELETE  FROM {interDBName}.{interSchemaName}.T_MT_WAC_DMEM;
-- MAGIC --04 AQ_WAC_Accounts_DMEM_PVP 
-- MAGIC -----------------------------------01 Q_WAC_Leads
-- MAGIC CREATE OR REPLACE VIEW V_WAC_LEADS_01 AS SELECT DISTINCT A.LEAD, A.LEAD_NAME, A.PVP_FLAG, A.WAC, A.EXPANSION
-- MAGIC FROM {coreDBName}.{coreSchemaName}.T_LUTL_PHS_LEADS AS A 
-- MAGIC WHERE (A.LEAD != '293388' AND A.WAC ='Yes');
-- MAGIC
-- MAGIC -----------------------------------02 Q_WAC_Accounts
-- MAGIC --------Data Issue needs to be resolved A.PVP_PARTICIPATION_FLAG Value should be Y , its true as of now 
-- MAGIC CREATE OR REPLACE VIEW V_WAC_ACCOUNTS_02 AS 
-- MAGIC SELECT A.CUST_ACCT_ID, A.CUST_ACCT_NAME, B.LEAD, B.LEAD_NAME, A.PHS_340B_ID, PVP_PARTICIPATION_FLAG, A.ENTITY_TYPE
-- MAGIC FROM {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS A , V_WAC_LEADS_01 AS B 
-- MAGIC WHERE ((A.PVP_PARTICIPATION_FLAG='Y') AND A.ENTITY_TYPE IN ('CAN','DSH','PED') 
-- MAGIC        AND (A.CUST_CHN_ID != '989') AND (A.ACCT_CLASSIFICATION='003') AND (UPPER(A.STATUS)='ACTIVE') 
-- MAGIC        AND (CHARINDEX('A34', A.CUST_ACCT_NAME)>0));
-- MAGIC 	   
-- MAGIC --04 AQ_WAC_Accounts_DMEM_PVP
-- MAGIC INSERT INTO {interDBName}.{interSchemaName}.T_MT_WAC_DMEM ( CUST_ACCT_ID, LEAD, LEAD_NAME, ENTITY_TYPE )
-- MAGIC SELECT A.CUST_ACCT_ID, A.LEAD,A.LEAD_NAME, A.ENTITY_TYPE
-- MAGIC FROM V_WAC_ACCOUNTS_02 AS A INNER JOIN V_WAC_LEADS_01 AS B ON (A.PVP_PARTICIPATION_FLAG = B.PVP_FLAG) AND (A.LEAD = B.LEAD);
-- MAGIC
-- MAGIC ------------------05 Q_WAC_DMEM_Missing
-- MAGIC CREATE OR REPLACE VIEW V_WAC_DMEM_MISSING_05 AS 
-- MAGIC SELECT DISTINCT A.CUST_ACCT_ID, C.CUST_ACCT_NAME, C.ZX_BLOCK, C.SALES_CURMTH, C.HRSA_START_DATE, C.HRSA_TERM_DATE, C.PVP_PARTICIPATION_FLAG AS PVP_FLAG, C.PVP_ELIGIBILITY_DATE, A.LEAD, A.LEAD_NAME, C.PHS_340B_ID, A.Expansion_Entity, A.ENTITY_TYPE, C.STATUS, C.CUST_CHN_ID FROM {interDBName}.{interSchemaName}.T_MT_WAC_DMEM AS A LEFT JOIN {interDBName}.{interSchemaName}.T_DMEM_LIST AS B ON ((A.LEAD = B.CNTRCT_LEAD_ID) AND (A.CUST_ACCT_ID = B.CUST_ACCT_ID)) INNER JOIN {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS C ON A.CUST_ACCT_ID = C.CUST_ACCT_ID
-- MAGIC WHERE (UPPER(C.STATUS)='ACTIVE' AND (C.CUST_CHN_ID != '989') AND (B.CUST_ACCT_ID IS NULL) AND (B.CNTRCT_LEAD_ID IS NULL))
-- MAGIC ORDER BY A.CUST_ACCT_ID;
-- MAGIC
-- MAGIC -----------------03 DQ_PHS_DMEM
-- MAGIC
-- MAGIC DELETE FROM {interDBName}.{interSchemaName}.T_MT_PHS_DMEM;
-- MAGIC
-- MAGIC ---------------04 AQ_PHS_Accounts_DMEM_Main       &     05 AQ_PHS_Accounts_DMEM_PVP
-- MAGIC -------------------------------------01 Q_PHS_Leads
-- MAGIC CREATE OR REPLACE VIEW V_PHS_LEADS_01 AS 
-- MAGIC SELECT DISTINCT A.LEAD, A.LEAD_NAME, A.PVP_Flag, A.PHS, A.Expansion
-- MAGIC FROM {coreDBName}.{coreSchemaName}.T_LUTL_PHS_LEADS AS A 
-- MAGIC WHERE ((A.LEAD != '293388') AND (A.PHS='Yes'));
-- MAGIC -------------------------------------02 Q_PHS_Accounts
-- MAGIC CREATE OR REPLACE VIEW V_PHS_ACCOUNTS_02 AS 
-- MAGIC SELECT A.CUST_ACCT_ID, A.CUST_ACCT_NAME,REPLACE(UPPER(A.PVP_PARTICIPATION_FLAG),'TRUE','Y') AS PVP_PARTICIPATION_FLAG, B.LEAD, B.LEAD_NAME, A.PHS_340B_ID, CASE
-- MAGIC     WHEN ENTITY_TYPE='RRC' THEN 'Y'
-- MAGIC 	WHEN ENTITY_TYPE='SCH' THEN 'Y'
-- MAGIC 	WHEN ENTITY_TYPE='CAN' THEN 'Y'
-- MAGIC 	WHEN ENTITY_TYPE='CAH' THEN 'Y'
-- MAGIC 	ELSE 'N'
-- MAGIC END AS Expansion_Entity, A.ENTITY_TYPE
-- MAGIC FROM {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS A, V_PHS_LEADS_01 as B 
-- MAGIC WHERE ((A.CUST_CHN_ID != '989') AND (A.ACCT_CLASSIFICATION in ('004','005')) AND (UPPER(A.STATUS)='ACTIVE'));
-- MAGIC
-- MAGIC INSERT INTO {interDBName}.{interSchemaName}.T_MT_PHS_DMEM ( CUST_ACCT_ID, LEAD, LEAD_NAME, Expansion_Entity, ENTITY_TYPE )
-- MAGIC SELECT A.CUST_ACCT_ID, A.LEAD, A.LEAD_NAME, A.Expansion_Entity, A.ENTITY_TYPE
-- MAGIC FROM V_PHS_ACCOUNTS_02 AS A INNER JOIN V_PHS_LEADS_01 AS B ON (A.LEAD = B.LEAD) AND ((A.Expansion_Entity = B.Expansion) OR (A.PVP_PARTICIPATION_FLAG = B.PVP_Flag));
-- MAGIC
-- MAGIC ------------05 AQ_PHS_Accounts_DMEM_PVP ... Merged with 4 
-- MAGIC --INSERT INTO T_MT_PHS_DMEM_TEMP ( CUST_ACCT_ID, LEAD, LEAD_NAME, Expansion_Entity, ENTITY_TYPE )
-- MAGIC ---SELECT A.CUST_ACCT_ID, A.LEAD, A.LEAD_NAME, A.Expansion_Entity, A.ENTITY_TYPE
-- MAGIC --FROM V_PHS_ACCOUNTS_02 AS A INNER JOIN V_PHS_LEADS_01 AS B ON (A.PVP_PARTICIPATION_FLAG = B.PVP_Flag) AND (A.LEAD = B.LEAD);
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC
-- MAGIC

-- COMMAND ----------

------------06 Q_PHS_DMEM_Missing
CREATE OR REPLACE VIEW V_PHS_DMEM_MISSING_06 AS 
SELECT A.CUST_ACCT_ID, C.CUST_ACCT_NAME, C.ZX_BLOCK, C.SALES_CURMTH, C.HRSA_START_DATE, C.HRSA_TERM_DATE, C.PVP_PARTICIPATION_FLAG AS PVP_Flag, C.PVP_ELIGIBILITY_DATE, A.LEAD, A.LEAD_NAME, C.PHS_340B_ID, A.Expansion_Entity, A.ENTITY_TYPE, C.COMMENTS, C.STATUS
FROM {interDBName}.{interSchemaName}.T_MT_PHS_DMEM AS A LEFT JOIN {interDBName}.{interSchemaName}.T_DMEM_LIST AS B ON (A.LEAD = B.CNTRCT_LEAD_ID) AND (A.CUST_ACCT_ID = B.CUST_ACCT_ID) INNER JOIN {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS C ON A.CUST_ACCT_ID = C.CUST_ACCT_ID
WHERE ((UPPER(C.STATUS)='ACTIVE') AND (B.CUST_ACCT_ID IS NULL) AND (B.CNTRCT_LEAD_ID IS NULL))
ORDER BY A.CUST_ACCT_ID;

-- COMMAND ----------

--------06 Q_WACA34_DMEM_Submission
CREATE OR REPLACE VIEW V_WACA34_DMEM_SUBMISSION_06 AS 
SELECT DISTINCT '' AS PPM, 'A' AS ADD, A.CUST_ACCT_ID, A.CUST_ACCT_NAME, B.LEAD, B.LEAD_NAME, '1' AS PRIORITY, 'Z' AS PREFERENCE, '' AS MARK_UP, '' AS CHANGE_BY, '' AS CHANGE_ON, 'N' AS BLOCK_ID, 'N' AS CONTRACT_BLOCK, A.SALES_CURMTH, A.HRSA_TERM_DATE, A.PVP_ELIGIBILITY_DATE, A.ZX_BLOCK, C.OPENED_FOR_RETURNS
FROM V_WAC_DMEM_MISSING_05 AS A INNER JOIN {coreDBName}.{coreSchemaName}.T_LUTL_PHS_LEADS AS B ON (A.LEAD = B.LEAD) INNER JOIN {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS C ON A.CUST_ACCT_ID = C.CUST_ACCT_ID;

-- COMMAND ----------


---------07 Q_PHS_DMEM_Submission
CREATE OR REPLACE VIEW V_PHS_DMEM_SUBMISSION_07 AS 
SELECT DISTINCT A.CUST_ACCT_ID, A.CUST_ACCT_NAME, B.LEAD, B.LEAD_NAME, B.DMEM_Prio, B.DMEM_Pref, A.PHS_340B_ID, A.SALES_CURMTH, A.HRSA_START_DATE, A.HRSA_TERM_DATE, A.PVP_ELIGIBILITY_DATE, A.ZX_BLOCK, C.OPENED_FOR_RETURNS, C.ROUTE, C.STOP, C.RX_BILL_PLAN, C.NATIONAL_GRP_CD, C.NATIONAL_GRP_NAME
FROM V_PHS_DMEM_MISSING_06 AS A INNER JOIN {coreDBName}.{coreSchemaName}.T_LUTL_PHS_LEADS AS B ON A.LEAD = B.LEAD INNER JOIN {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS C ON A.CUST_ACCT_ID = C.CUST_ACCT_ID;

-- COMMAND ----------

----------LUQ_ACCOUNT_DMEM_ADHOC ------------------LUQ_ACCOUNT2....... How its populating--PART 4 
--CREATE TABLE IF NOT EXISTS T_LUQ_ACCOUNT(ID INT, Account VARCHAR(16777216));

--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(429, '170294');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(430, '184889');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(431, '719578');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(432, '220885');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(433, '166 572');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(434, '081930');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(435, '347197');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(436, '829046');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(437, '243264');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(438, '800175');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(439, '209722');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(440, '734286');
--INSERT INTO T_LUQ_ACCOUNT2(ID,Account) values(441, '264571');

-- COMMAND ----------

CREATE OR REPLACE VIEW V_LUQ_ACCOUNT_DMEM_ADHOC AS 
SELECT DISTINCT C.CUST_ACCT_ID, C.CUST_ACCT_NAME, B.CNTRCT_LEAD_ID, B.LEAD_NAME AS T_DMEM_LIST_LEAD_NAME, B.LEAD_TYPE, B.MARKUP_CONT, B.CONT_PREFD, D.LEAD_NAME AS LUTL_PHS_LEADS_LEAD_NAME 
FROM {coreDBName}.{coreSchemaName}.T_LUQ_ACCOUNT AS A INNER JOIN {interDBName}.{interSchemaName}.T_DMEM_LIST AS B ON A.Account = B.CUST_ACCT_ID INNER JOIN {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS C ON A.Account = C.CUST_ACCT_ID LEFT JOIN {coreDBName}.{coreSchemaName}.T_LUTL_PHS_LEADS AS D ON B.CNTRCT_LEAD_ID = D.LEAD;

-- COMMAND ----------

--------------------LUQ_Account_DMEM_Submission_WACA34 ------ PART 5
--CREATE TABLE IF NOT EXISTS T_LUQ_ACCOUNT2(ID INT, Account VARCHAR(16777216));
CREATE OR REPLACE VIEW V_LUQ_ACCOUNT_DMEM_SUBMISSION_WACA34 AS 
SELECT DISTINCT B.PPM, B.ADD, B.CUST_ACCT_ID, B.CUST_ACCT_NAME, B.LEAD, B.LEAD_NAME, B.PRIORITY, B.PREFERENCE, B.MARK_UP, B.CHANGE_BY, B.CHANGE_ON, B.BLOCK_ID, B.CONTRACT_BLOCK, B.SALES_CURMTH, B.HRSA_TERM_DATE, B.PVP_ELIGIBILITY_DATE, B.ZX_BLOCK
FROM {coreDBName}.{coreSchemaName}.T_LUQ_ACCOUNT AS A INNER JOIN V_WACA34_DMEM_SUBMISSION_06 AS B ON A.ACCOUNT = B.CUST_ACCT_ID;

-- COMMAND ----------


--Success
CREATE OR REPLACE VIEW V_SUCCESS AS select pi() * 2.0 * 2.0 as area_of_circle;
