-- Databricks notebook source
-- MAGIC %md
-- MAGIC This uses  data source from PSAS_DB

-- COMMAND ----------

CREATE OR REPLACE TABLE psas_di_dev.340b_gold.T_ISMC_MHS_AUDIT AS
SELECT CA.CUST_ACCT_ID, CA.CUST_ACCT_NAM, CA.ACCT_CHN_ID, V.MCK_KU_CHNL_TYP, V.MCK_KU_ACCT_CLAS, 
CA.NATL_GRP_CD, M.NATL_GRP_NAM 
FROM dev_psas_db.RPT.T_IW_CUST_ACCT CA INNER JOIN dev_psas_db.RPT.T_DM_VSTX_CUST V 
ON CA.CUST_ACCT_ID = V.CUST_ACCT_ID 
INNER JOIN psas_di_dev.340b_gold.mhs_rna_cust_acct M 
ON M.CUST_ACCT_ID = CA.CUST_ACCT_ID 
WHERE ACTIVE_CUST_IND = 'A'  
AND CA.ACCT_CHN_ID <> '000' 
AND ((V.MCK_KU_ACCT_CLAS = '001' AND V.MCK_KU_CHNL_TYP = '20') OR 
(V.MCK_KU_ACCT_CLAS IN ('003','004','005') AND V.MCK_KU_CHNL_TYP = '30'));
