-- Databricks notebook source
truncate table psas_di_dev.340b_gold.T_PHS_AUDIT_PART2;

-- COMMAND ----------

INSERT INTO psas_di_dev.340b_gold.t_phs_audit_part3 (
    CUST_ACCT_ID,
    CUST_ACCT_NAME,
    ACCT_CLASSIFICATION,
    CUST_CHN_ID,
    CHAIN_NAM,
    NATIONAL_GRP_CD,
    NATIONAL_GRP_NAME,
    NATIONAL_SUBGRP_CD,
    NATIONAL_SUBGRP_NAME,
    REGION_CD,
    REGION_NAME,
    DELIVERY_DOC,
    DIST_CHANNEL,
    HOME_DC_ID,
    DC_NAME,
    PHS_340B_ID,
    PHS_340B_ID_NOSUFFIX,
    DEA_FAMILY,
    STATUS,
    UPDATE_SAP,
    MNC,
    COVERED_ENTITY_PRIMARY,
    CONTRACT_PHARMACY_NAME,
    CONTRACT_PHARMACY_PRIMARY,
    DSCSA_RECEIVED,
    ACTIVATION_DATE,
    ACCT_NAME_PHS,
    ENTITY_TYPE,
    AUDIT_GPO,
    AGREEMENT,
    AGREEMENT_EXPIRATION,
    CAN_NAM,
    AUDIT_GROUP_NAME,
    AUDIT_COMMENTS,
    AUDIT_STATUS,
    RETURNS_MATRIX,
    SALES_ADMIN,
    MHS_SALES_REP,
    RX_COGS,
    OTC_COGS,
    COMMENTS,
    SALES_REP,
    SALES_LSTMTH,
    SALES_CURMTH,
    ADDR_DELIVERY,
    ADDR_INVOICE,
    DEA_NUM,
    BUS_TYP_CD,
    RX_BILL_PLAN,
    ROUTE,
    STOP,
    GPO_ID,
    GPO_ACCT,
    THIRD_PARTY_VENDOR,
    ZX_BLOCK,
    OPENED_FOR_RETURNS,
    UPDATE_ACTIVESTATUS,
    UPDATE_340BID,
    FIRST_ORDER,
    LAST_ORDER,
    ENTITY_TYPE_NAME,
    PVP_CODE,
    PVP_CODING,
    ACM_NAME,
    HRSA_START_DATE,
    HRSA_TERM_DATE,
    COVERED_ENTITY_NAME,
    PVP_MEMBER_NAME,
    PVP_PARTICIPANT_ID,
    PVP_PARTICIPATION_FLAG,
    PVP_ELIGIBILITY_DATE,
    PVP_EXPIRATION_DATE,
    CE_CITY,
    CE_STATE
)
SELECT 
    T_PHS_AUDIT.CUST_ACCT_ID, 
    T_PHS_AUDIT.CUST_ACCT_NAME, 
    T_PHS_AUDIT.ACCT_CLASSIFICATION, 
    T_PHS_AUDIT.CUST_CHN_ID, 
    T_PHS_AUDIT.CHAIN_NAM, 
    T_PHS_AUDIT.NATIONAL_GRP_CD, 
    T_PHS_AUDIT.NATIONAL_GRP_NAME, 
    T_PHS_AUDIT.NATIONAL_SUBGRP_CD, 
    T_PHS_AUDIT.NATIONAL_SUBGRP_NAME, 
    T_PHS_AUDIT.REGION_CD, 
    T_PHS_AUDIT.REGION_NAME, 
    T_PHS_AUDIT.DELIVERY_DOC, 
    T_PHS_AUDIT.DIST_CHANNEL, 
    T_PHS_AUDIT.HOME_DC_ID, 
    LUTL_SALES_ADMIN.Location AS DC_NAME, 
    T_PHS_AUDIT.PHS_340B_ID, 
    CASE 
        WHEN (T_PHS_AUDIT.PHS_340B_ID IS NOT NULL AND T_PHS_AUDIT.PHS_340B_ID <> '') 
             AND CHARINDEX('-', T_PHS_AUDIT.PHS_340B_ID) > 0 
        THEN LEFT(T_PHS_AUDIT.PHS_340B_ID, CHARINDEX('-', T_PHS_AUDIT.PHS_340B_ID) - 1)
        ELSE T_PHS_AUDIT.PHS_340B_ID
    END AS PHS_340B_ID_NOSUFFIX,
    T_PHS_AUDIT.DEA_FAMILY, 
    -- IFF(ACTIVE_CUST_IND = 'A', 'ACTIVE', 'INACTIVE') AS STATUS, 
    T_PHS_AUDIT.UPDATE_SAP, 
    '' AS MNC, 
    T_Pharmacy_Type_Data.CE_Primary AS COVERED_ENTITY_PRIMARY,
    T_Pharmacy_Type_Data.Pharmacy_Name AS CONTRACT_PHARMACY_NAME,
    T_Pharmacy_Type_Data.CP_Primary AS CONTRACT_PHARMACY_PRIMARY, 
    T_Pharmacy_Type_Data.DSCSA_RECEIVED, 
    T_PHS_AUDIT.ACTIVATION_DATE, 
    CASE 
        WHEN (CHARINDEX(' PHS', T_PHS_AUDIT.CUST_ACCT_NAME) > 0) OR 
             ((CHARINDEX('PHS', T_PHS_AUDIT.CUST_ACCT_NAME) > 0) AND (LEFT(T_PHS_AUDIT.CUST_ACCT_NAME, 5) <> 'USPHS') AND (CHARINDEX('JOSEPHS', T_PHS_AUDIT.CUST_ACCT_NAME) = 0))
        THEN 'Y'
        ELSE 'N'
    END AS ACCT_NAME_PHS, 
    CASE 
        WHEN LEFT(T_PHS_AUDIT.PHS_340B_ID, 3) IN ('CH0','CH1') OR LEFT(T_PHS_AUDIT.PHS_340B_ID, 2) IN ('FP','HM','HV','NH','TB','UI','RW')
        THEN LEFT(T_PHS_AUDIT.PHS_340B_ID, 2)
        ELSE T_PHS_AUDIT.ENTITY_TYPE
    END AS ENTITY_TYPE,
    T_Quarterly_Audit_Data.GPO AS AUDIT_GPO,
    T_Quarterly_Audit_Data.Agreement, 
    T_Quarterly_Audit_Data.Agreement_Expiration, 
    CASE WHEN T_Quarterly_Audit_Data.CAN_NAME <> '-' THEN T_Quarterly_Audit_Data.CAN_NAME ELSE '' END AS CAN_NAM, 
    T_Quarterly_Audit_Data.GROUP_NAME AS AUDIT_GROUP_NAME, 
    T_Quarterly_Audit_Data.COMMENTS AS AUDIT_COMMENTS, 
    T_Quarterly_Audit_Data.AUDIT_STATUS, 
    T_Quarterly_Audit_Data.Returns_Matrix,
    LUTL_SALES_ADMIN.Sales_Admin, 
    LUTL_SALES_ADMIN.MHS_Sales AS MHS_SALES_REP, 
    T_PHS_AUDIT.RX_COGS, 
    T_PHS_AUDIT.OTC_COGS, 
    T_PHS_AUDIT.COMMENTS, 
    T_PHS_AUDIT.SALES_REP, 
    T_PHS_AUDIT.SALES_LSTMTH, 
    T_PHS_AUDIT.SALES_CURMTH, 
    T_PHS_AUDIT.ADDR_DELIVERY,
    T_PHS_AUDIT.ADDR_INVOICE, 
    T_PHS_AUDIT.DEA_NUM,
    T_PHS_AUDIT.BUS_TYP_CD, 
    T_PHS_AUDIT.RX_BILL_PLAN, 
    T_PHS_AUDIT.ROUTE,
    T_PHS_AUDIT.STOP, 
    T_PHS_AUDIT.GPO_ID, 
    T_PHS_AUDIT.GPO_ACCT,
    T_TPV.Vendor_Name AS THIRD_PARTY_VENDOR, 
    T_PHS_AUDIT.ZX_BLOCK, 
    T_PHS_AUDIT.OPENED_FOR_RETURNS,
    T_PHS_AUDIT.UPDATE_ACTIVESTATUS, 
    T_PHS_AUDIT.UPDATE_340BID, 
    T_PHS_AUDIT.FIRST_ORDER, 
    T_PHS_AUDIT.LAST_ORDER,
    CASE 
        WHEN T_PHS_AUDIT.ENTITY_TYPE = LUTL_ENTITY.ENTITY_TYPE
        THEN LUTL_ENTITY.ENTITY_NAME
        ELSE ENTITY_TYPE_NAME
    END AS ENTITY_TYPE_NAME,
    CASE 
        WHEN (ACCT_CLASSIFICATION = '003' OR ACCT_CLASSIFICATION IN ('004', '005')) 
             OR (NATIONAL_GRP_CD = '0240' AND UPPER(T_PHS_AUDIT.STATUS) = 'ACTIVE')
        THEN CUST_CHN_ID || CASE WHEN TRIM(NATIONAL_SUBGRP_CD) <> '' THEN NATIONAL_SUBGRP_CD ELSE '000000' END
        ELSE PVP_CODE
    END AS PVP_CODE,
    CASE 
        WHEN (ACCT_CLASSIFICATION = '003' OR ACCT_CLASSIFICATION IN ('004', '005')) 
             OR (NATIONAL_GRP_CD = '0240')
        THEN CASE WHEN LUTL_PVP_CODING.PVP_CODING = 'Y' THEN 'Y' ELSE 'N' END
        ELSE T_PHS_AUDIT.PVP_CODING
    END AS PVP_CODING,
    CASE 
        WHEN MNC_PHS.MEM = 'A34' THEN 'A34'
        WHEN MNC_PHS.MEM = 'C34' THEN T_PHS_AUDIT.MNC || 'C34'
        ELSE MNC
    END AS MNC,
    CASE 
        WHEN T_PHS_AUDIT.CUST_ACCT_ID = Nat_Grp.CUSID THEN Nat_Grp.ACM
        ELSE ACM_NAME
    END AS ACM_NAME,
    CASE 
        WHEN T_PHS_AUDIT.PHS_340B_ID = T_HRSA.PHS_340B_ID THEN T_HRSA.HRSA_START_DATE
        ELSE T_PHS_AUDIT.HRSA_START_DATE
    END AS HRSA_START_DATE,
    CASE 
        WHEN T_PHS_AUDIT.PHS_340B_ID = T_HRSA.PHS_340B_ID THEN T_HRSA.HRSA_TERM_DATE
        ELSE T_PHS_AUDIT.HRSA_TERM_DATE
    END AS HRSA_TERM_DATE,
    CASE 
        WHEN T_PHS_AUDIT.PHS_340B_ID = T_HRSA.PHS_340B_ID THEN T_HRSA.COVERED_ENTITY
        ELSE T_PHS_AUDIT.COVERED_ENTITY_NAME
    END AS COVERED_ENTITY_NAME,
    CASE 
        WHEN (T_PHS_AUDIT.ACCT_CLASSIFICATION = '003' OR T_PHS_AUDIT.ACCT_CLASSIFICATION IN ('004', '005')) THEN ''
        ELSE T_PHS_AUDIT.PVP_MEMBER_NAME
    END AS PVP_MEMBER_NAME,
    CASE 
        WHEN (T_PHS_AUDIT.ACCT_CLASSIFICATION = '003' OR T_PHS_AUDIT.ACCT_CLASSIFICATION IN ('004', '005')) THEN ''
        ELSE T_PHS_AUDIT.PVP_PARTICIPANT_ID
    END AS PVP_PARTICIPANT_ID,
    CASE 
        WHEN (T_PHS_AUDIT.ACCT_CLASSIFICATION = '003' OR T_PHS_AUDIT.ACCT_CLASSIFICATION IN ('004', '005')) THEN 'N'
        ELSE T_PHS_AUDIT.PVP_PARTICIPATION_FLAG
    END AS PVP_PARTICIPATION_FLAG,
    CASE 
        WHEN (T_PHS_AUDIT.ACCT_CLASSIFICATION = '003' OR T_PHS_AUDIT.ACCT_CLASSIFICATION IN ('004', '005')) THEN NULL
        ELSE T_PHS_AUDIT.PVP_ELIGIBILITY_DATE
    END AS PVP_ELIGIBILITY_DATE,
    CASE 
        WHEN (T_PHS_AUDIT.ACCT_CLASSIFICATION = '003' OR T_PHS_AUDIT.ACCT_CLASSIFICATION IN ('004', '005')) THEN NULL
        ELSE T_PHS_AUDIT.PVP_EXPIRATION_DATE
    END AS PVP_EXPIRATION_DATE,
    CASE 
        WHEN (T_PHS_AUDIT.ACCT_CLASSIFICATION = '003' OR T_PHS_AUDIT.ACCT_CLASSIFICATION IN ('004', '005')) THEN ''
        ELSE T_PHS_AUDIT.CE_CITY
    END AS CE_CITY,
    CASE 
        WHEN (T_PHS_AUDIT.ACCT_CLASSIFICATION = '003' OR T_PHS_AUDIT.ACCT_CLASSIFICATION IN ('004', '005')) THEN ''
        ELSE T_PHS_AUDIT.CE_STATE
    END AS CE_STATE
FROM 
    psas_di_dev.340b_brnz.T_PHS_AUDIT AS T_PHS_AUDIT 
LEFT JOIN psas_di_dev.340b_brnz.T_LUTL_SALES_ADMIN AS LUTL_SALES_ADMIN 
    ON T_PHS_AUDIT.HOME_DC_ID = LUTL_SALES_ADMIN.DC 
LEFT JOIN psas_di_dev.340b_brnz.T_QUARTERLY_AUDIT_DATA AS T_Quarterly_Audit_Data 
    ON T_PHS_AUDIT.CUST_ACCT_ID = T_Quarterly_Audit_Data.Cust_Acct_ID 
LEFT JOIN psas_di_dev.340b_brnz.T_PHARMACY_TYPE_DATA AS T_Pharmacy_Type_Data 
    ON T_PHS_AUDIT.CUST_ACCT_ID = T_Pharmacy_Type_Data.Cust_Acct
LEFT JOIN psas_di_dev.340b_brnz.T_PHS_MEMBERSHIPROSTER_MEMBERS AS T_PHS_MembershipRoster_Members 
    ON T_PHS_AUDIT.CUST_ACCT_ID = T_PHS_MembershipRoster_Members.CUST_ACCT_ID
LEFT JOIN psas_di_dev.340b_brnz.T_TPV AS T_TPV 
    ON T_PHS_MembershipRoster_Members.THIRD_PARTY_VENDOR = T_TPV.TPV
LEFT JOIN psas_di_dev.340b_brnz.T_LUTL_ENTITY AS LUTL_ENTITY 
    ON T_PHS_AUDIT.ENTITY_TYPE = LUTL_ENTITY.ENTITY_TYPE
LEFT JOIN psas_di_dev.340b_brnz.T_LUTL_PVP_CODING AS LUTL_PVP_CODING 
    ON T_PHS_AUDIT.PVP_CODE = LUTL_PVP_CODING.Coding
LEFT JOIN psas_di_dev.340b_brnz.T_MNC_PHS AS MNC_PHS 
    ON MNC_PHS.CUSTOMER = T_PHS_AUDIT.CUST_ACCT_ID
LEFT JOIN psas_di_dev.340b_brnz.T_Nat_Grp AS Nat_Grp 
    ON T_PHS_AUDIT.CUST_ACCT_ID = Nat_Grp.CUSID
LEFT JOIN psas_di_dev.340b_brnz.t_hrsa AS T_HRSA 
    ON T_PHS_AUDIT.PHS_340B_ID = T_HRSA.PHS_340B_ID
LEFT JOIN psas_di_dev.340b_brnz.t_mt_pvp_report AS MT_PVP_REPORT 
    ON T_PHS_AUDIT.PHS_340B_ID = MT_PVP_REPORT.PVP_340B_ID
LEFT JOIN psas_di_dev.340b_brnz.t_mt_pvp_report_parentmatch AS MT_PVP_REPORT_PARENTMATCH 
    ON T_PHS_AUDIT.PHS_340B_ID = MT_PVP_REPORT_PARENTMATCH.PVP_340B_ID
WHERE 
    T_PHS_AUDIT.CUST_ACCT_ID IS NOT NULL;
