-- Databricks notebook source

CREATE OR REPLACE VIEW psas_di_dev.340b_gold.V_NON_ORDERING_ACCOUNTS AS 
SELECT LUNOORAC.Cust_Acct_ID, PHAUD.CUST_ACCT_NAME, PHAUD.CUST_CHN_ID, PHAUD.STATUS
FROM psas_di_dev.340b_brnz.t_lutl_non_ordering_accounts AS LUNOORAC LEFT JOIN psas_di_dev.340b_brnz.t_phs_audit AS PHAUD ON LUNOORAC.Cust_Acct_ID = PHAUD.CUST_ACCT_ID;


-- COMMAND ----------

CREATE OR REPLACE VIEW psas_di_dev.340b_gold.V_ACCOUNT_CLASSIFICATION_02 AS 
SELECT DISTINCT PHAUD.CUST_ACCT_ID, PHAUD.CUST_ACCT_NAME, PHAUD.ROUTE, PHAUD.STOP, PHAUD.ACTIVATION_DATE, PHAUD.UPDATE_SAP, PHAUD.PHS_340B_ID, PHAUD.CUST_CHN_ID, PHAUD.ACCT_CLASSIFICATION, PHAUD.NATIONAL_GRP_CD, PHAUD.STATUS, PHAUD.PVP_CODING, PHAUD.COMMENTS
FROM psas_di_dev.340b_brnz.T_PHS_AUDIT  AS PHAUD LEFT JOIN psas_di_dev.340b_gold.V_NON_ORDERING_ACCOUNTS AS NOORAC ON PHAUD.CUST_ACCT_ID = NOORAC.Cust_Acct_ID
WHERE (PHAUD.CUST_CHN_ID In ('147','586','889') AND PHAUD.CUST_CHN_ID Not In ('989','585') AND PHAUD.ACCT_CLASSIFICATION not in ('004','005') AND 
UPPER(PHAUD.STATUS)='ACTIVE' AND CHARINDEX('Y',CONCAT(ACCT_NAME_A34,ACCT_NAME_A34))=0 AND NOORAC.Cust_Acct_ID Is Null) OR 
(PHAUD.CUST_CHN_ID In ('147','586','889') AND PHAUD.CUST_CHN_ID Not In ('989','585') AND PHAUD.ACCT_CLASSIFICATION not in ('004','005') AND 
PHAUD.NATIONAL_GRP_CD='0240' AND UPPER(PHAUD.STATUS)='ACTIVE' AND CHARINDEX('Y',CONCAT(ACCT_NAME_A34,ACCT_NAME_A34))=0 AND 
NOORAC.Cust_Acct_ID Is Null) OR (PHAUD.CUST_CHN_ID In ('147','586','889') AND PHAUD.CUST_CHN_ID Not In ('989','585') AND 
PHAUD.ACCT_CLASSIFICATION != '003' AND PHAUD.NATIONAL_GRP_CD='0240' AND UPPER(PHAUD.STATUS)='ACTIVE' AND 
CHARINDEX('Y',CONCAT(ACCT_NAME_A34,ACCT_NAME_A34))=1 AND NOORAC.Cust_Acct_ID Is Null) OR (PHAUD.CUST_CHN_ID In ('147','586','889') 
AND PHAUD.CUST_CHN_ID Not In ('989','585') AND PHAUD.ACCT_CLASSIFICATION != '003' AND UPPER(PHAUD.STATUS)='ACTIVE' 
AND CHARINDEX('Y',CONCAT(ACCT_NAME_A34,ACCT_NAME_A34))=1 AND NOORAC.Cust_Acct_ID Is Null) OR (PHAUD.ACCT_CLASSIFICATION Not In ('003','004','005') 
AND UPPER(PHAUD.STATUS)='ACTIVE' AND PHAUD.PVP_CODING='Y' AND NOORAC.Cust_Acct_ID Is Null);
