-- Databricks notebook source
-- MAGIC %md
-- MAGIC This uses  data source from PSAS_DB

-- COMMAND ----------

CREATE OR REPLACE VIEW V_ISMC_MHS_AUDIT AS
SELECT CA.CUST_ACCT_ID, CA.CUST_ACCT_NAM, CA.ACCT_CHN_ID, V.MCK_KU_CHNL_TYP, V.MCK_KU_ACCT_CLAS, 
CA.NATL_GRP_CD, M.NATL_GRP_NAM 
FROM PRD_PSAS_DB.RPT.T_IW_CUST_ACCT CA INNER JOIN PRD_PSAS_DB.RPT.T_DM_VSTX_CUST V 
ON CA.CUST_ACCT_ID = V.CUST_ACCT_ID 
INNER JOIN SBX_PSAS_DB.MHS_RNA.MHS_RNA_CUST_ACCT M 
ON M.CUST_ACCT_ID = CA.CUST_ACCT_ID 
WHERE ACTIVE_CUST_IND = 'A'  
AND CA.ACCT_CHN_ID <> '000' 
AND ((V.MCK_KU_ACCT_CLAS = '001' AND V.MCK_KU_CHNL_TYP = '20') OR 
(V.MCK_KU_ACCT_CLAS IN ('003','004','005') AND V.MCK_KU_CHNL_TYP = '30'));
