# Databricks notebook source

--creating view for  V_PHS_Accounts_Non_AGP_Duplicates
CREATE OR REPLACE VIEW V_PHS_ACCOUNTS_NON_AGP_DUPLICATES_03 AS
SELECT TPANA.ACCOUNTS 
  FROM {coreDBName}.{coreSchemaName}.T_PHS_ACCOUNTS_NON_AGP AS TPANA
 GROUP BY TPANA.ACCOUNTS 
HAVING COUNT(TPANA.ACCOUNTS) > 1;

# COMMAND ----------

--04 Q_PHS_Accounts_Non_AGP_Coding
CREATE OR REPLACE VIEW V_PHS_ACCOUNTS_NON_AGP_CODING_04 AS
SELECT DISTINCT T_PHS_ACCOUNTS_NON_AGP.ACCOUNTS, T_PHS_AUDIT.CHAIN_NAM, T_PHS_AUDIT.NATIONAL_SUBGRP_NAME, T_PHS_AUDIT.ACCT_CLASSIFICATION, T_PHS_AUDIT.PHS_340B_ID, T_PHS_AUDIT.HRSA_TERM_DATE, T_PHS_AUDIT.PVP_PARTICIPANT_ID, T_PHS_AUDIT.PVP_ELIGIBILITY_DATE, T_PHS_AUDIT.PVP_PARTICIPATION_FLAG, T_PHS_AUDIT.PVP_CODING, T_PHS_AUDIT.STATUS, 
IFF(V_PHS_ACCOUNTS_NON_AGP_DUPLICATES_03.ACCOUNTS IS NULL ,'','Yes') AS Duplicate
FROM ({coreDBName}.{coreSchemaName}.T_PHS_ACCOUNTS_NON_AGP AS T_PHS_ACCOUNTS_NON_AGP LEFT JOIN {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS T_PHS_AUDIT  ON T_PHS_ACCOUNTS_NON_AGP.ACCOUNTS = T_PHS_AUDIT.CUST_ACCT_ID)
LEFT JOIN V_PHS_ACCOUNTS_NON_AGP_DUPLICATES_03 ON T_PHS_ACCOUNTS_NON_AGP.ACCOUNTS = V_PHS_ACCOUNTS_NON_AGP_DUPLICATES_03.ACCOUNTS
ORDER BY T_PHS_ACCOUNTS_NON_AGP.ACCOUNTS;
