# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE OR REPLACE VIEW V_ACCOUNTCONFIRMATION_LOOKUP_01 AS 
# MAGIC SELECT DISTINCT T_APEXUSFILE.SHIP_TO_ACCT_NO, T_APEXUSFILE.ENTITY_NAME, T_APEXUSFILE.SHIP_TO_ACCT_NAME, T_APEXUSFILE.APEXUS_340B_ID, T_PHS_AUDIT.CUST_ACCT_ID, T_PHS_AUDIT.CUST_ACCT_NAME, T_PHS_AUDIT.STATUS
# MAGIC FROM {coreDBName}.{coreSchemaName}.T_APEXUSFILE AS T_APEXUSFILE LEFT JOIN {coreDBName}.{coreSchemaName}.T_PHS_AUDIT AS T_PHS_AUDIT ON T_APEXUSFILE.SHIP_TO_ACCT_NO = T_PHS_AUDIT.CUST_ACCT_ID
# MAGIC WHERE T_APEXUSFILE.SHIP_TO_ACCT_NO IS NOT NULL
# MAGIC ORDER BY T_PHS_AUDIT.CUST_ACCT_ID;
# MAGIC
# MAGIC
