# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE OR REPLACE VIEW V_APEXUS_CODE_KEY_01 AS 
# MAGIC SELECT DISTINCT APCOKEY.Lead_No AS Lead_No, APCOKEY.Org_ID_Seq, APCOKEY.Contract_Name AS Contract_Name, APCOKEY.Material, APCOKEY.EAN_UPC, APCOKEY.Material_Description AS Material_Description, APCOKEY.Original_Valid_From AS Original_Valid_From, APCOKEY.Original_Valid_To AS Original_Valid_To, APCOKEY.Bid_Price AS Bid_Price, APCOKEY.GPO_Chbk_Ref_No AS GPO_Chbk_Ref_No
# MAGIC FROM {coreDBName}.{coreSchemaName}.T_APEXUS_CODE_KEY AS APCOKEY 
# MAGIC WHERE (APCOKEY.Lead_No Is Not Null);
# MAGIC
# MAGIC

# COMMAND ----------

--04 Q_APEXUS_WAC_ACCT_BY_LEAD
CREATE OR REPLACE VIEW V_APEXUS_WAC_ACCT_BY_LEAD_04 AS 
SELECT DISTINCT APWAACBYLE.Lead_No AS Lead_No, APWAACBYLE.Org_ID_Seq, APWAACBYLE.Contract_Name AS Contract_Name, APWAACBYLE.Material, APWAACBYLE.EAN_UPC, APWAACBYLE.Material_Description AS Material_Description, APWAACBYLE.Original_Valid_From AS Original_Valid_From, APWAACBYLE.Original_Valid_To AS Original_Valid_To, APWAACBYLE.Bid_Price AS Bid_Price, APWAACBYLE.GPO_Chbk_Ref_No AS GPO_Chbk_Ref_No
FROM {coreDBName}.{coreSchemaName}.T_APEXUS_WAC_ACCT_BY_LEAD AS APWAACBYLE;


# COMMAND ----------

--02 Q_APEXUS_PHS_ACCT_BY_LEAD
CREATE OR REPLACE VIEW V_APEXUS_PHS_ACCT_BY_LEAD_02 AS 
SELECT DISTINCT APPHACBYLE.Lead_No AS Lead_No, APPHACBYLE.Org_ID_Seq, APPHACBYLE.Contract_Name AS Contract_Name, APPHACBYLE.Material, APPHACBYLE.EAN_UPC, APPHACBYLE.Material_Description AS Material_Description, APPHACBYLE.Original_Valid_From AS Original_Valid_From, APPHACBYLE.Original_Valid_To AS Original_Valid_To, APPHACBYLE.Bid_Price AS Bid_Price, APPHACBYLE.GPO_Chbk_Ref_No AS GPO_Chbk_Ref_No
FROM {coreDBName}.{coreSchemaName}.T_APEXUS_PHS_ACCT_BY_LEAD AS APPHACBYLE 
WHERE (APPHACBYLE.Lead_No Is Not Null);


# COMMAND ----------

--05 Q_WAC_ACCOUNTS
CREATE OR REPLACE VIEW V_WAC_ACCOUNTS_05 AS 
SELECT VAPCOKEY.Lead_No, VAPCOKEY.Org_ID_Seq, VAPCOKEY.Contract_Name, VAPCOKEY.Material, VAPCOKEY.EAN_UPC, VAPCOKEY.Material_Description, VAPCOKEY.Original_Valid_From, VAPCOKEY.Original_Valid_To, VAPCOKEY.Bid_Price, VAPCOKEY.GPO_Chbk_Ref_No
FROM V_APEXUS_CODE_KEY_01 AS VAPCOKEY 
UNION SELECT VAPWAACBYLE.Lead_No, VAPWAACBYLE.Org_ID_Seq, VAPWAACBYLE.Contract_Name, VAPWAACBYLE.Material, VAPWAACBYLE.EAN_UPC, VAPWAACBYLE.Material_Description, VAPWAACBYLE.Original_Valid_From, VAPWAACBYLE.Original_Valid_To, VAPWAACBYLE.Bid_Price, VAPWAACBYLE.GPO_Chbk_Ref_No
FROM V_APEXUS_WAC_ACCT_BY_LEAD_04 AS VAPWAACBYLE;


# COMMAND ----------

--03 Q_PHS_ACCOUNTS
CREATE OR REPLACE VIEW V_PHS_ACCOUNTS_03 AS 
SELECT VAPCOKEY.Lead_No, VAPCOKEY.Org_ID_Seq, VAPCOKEY.Contract_Name, VAPCOKEY.Material, VAPCOKEY.EAN_UPC, VAPCOKEY.Material_Description, VAPCOKEY.Original_Valid_From, VAPCOKEY.Original_Valid_To, VAPCOKEY.Bid_Price, VAPCOKEY.GPO_Chbk_Ref_No
FROM V_APEXUS_CODE_KEY_01 AS VAPCOKEY 
UNION SELECT VAPPHACBYLE.Lead_No, VAPPHACBYLE.Org_ID_Seq, VAPPHACBYLE.Contract_Name, VAPPHACBYLE.Material, VAPPHACBYLE.EAN_UPC, VAPPHACBYLE.Material_Description, VAPPHACBYLE.Original_Valid_From, VAPPHACBYLE.Original_Valid_To, VAPPHACBYLE.Bid_Price, VAPPHACBYLE.GPO_Chbk_Ref_No
FROM V_APEXUS_PHS_ACCT_BY_LEAD_02 AS VAPPHACBYLE;


# COMMAND ----------

--04b Q_WAC_ACCT_BY_LEAD_Check
CREATE OR REPLACE VIEW V_WAC_ACCT_BY_LEAD_CHECK_04B AS 
SELECT DISTINCT VAPWAACBYLE.Lead_No, LUPHLEAD.LEAD_Unformatted, LUPHLEAD.WAC
FROM V_APEXUS_WAC_ACCT_BY_LEAD_04  AS VAPWAACBYLE LEFT JOIN {coreDBName}.{coreSchemaName}.T_LUTL_PHS_LEADS AS LUPHLEAD ON VAPWAACBYLE.Lead_No = LUPHLEAD.LEAD_Unformatted
ORDER BY VAPWAACBYLE.Lead_No;
--02b Q_PHS_ACCT_BY_LEAD_Check
CREATE OR REPLACE VIEW V_PHS_ACCT_BY_LEAD_CHECK_02B AS 
SELECT DISTINCT VAPPHACBYLE.Lead_No, LUPHLEAD.LEAD_Unformatted, LUPHLEAD.PHS
FROM V_APEXUS_PHS_ACCT_BY_LEAD_02  AS VAPPHACBYLE LEFT JOIN {coreDBName}.{coreSchemaName}.T_LUTL_PHS_LEADS AS LUPHLEAD ON VAPPHACBYLE.Lead_No = LUPHLEAD.LEAD_Unformatted
ORDER BY VAPPHACBYLE.Lead_No;
